# Generated by Django 6.1.1 on 2026-09-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км)')),
                ('transmission', models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механика'), ('robot', 'Робот'), ('variator', 'Вариатор')], max_length=20, verbose_name='Коробка передач')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], default='petrol', max_length=20, verbose_name='Топливо')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя (л)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Главное фото')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
